First official PR
myrfy001/dtld-rdma-driver pull request #2
Opened 2023-09-28 09:22 UTC by myrfy001

This is the first PR to review for the datenlords' kernelspace rdma driver.

2023-10-09 13:22 UTC, EAimTY requested changes

2023-10-09 13:22 UTC, EAimTY commented on driver/dtld.c
> +	return err;
The logic to free xdma resources may be missing here

2023-10-09 13:22 UTC, EAimTY commented on driver/dtld_verbs.h
> +    struct dtld_pool_elem elem;
This should be removed

2023-10-09 13:29 UTC, EAimTY commented
I am pushing some changes

2023-10-11 08:37 UTC, EAimTY approved these changes

2023-10-15 01:35 UTC, ruiqurm approved these changes

2023-10-15 01:35 UTC, ruiqurm commented on driver/dtld.c
> +        return -ENOMEM;
OK. I will make another commit to move `xpdev_alloc` into `xdma_device_open`.  I wonder why multi `xdev` may bind to the same `pdev`? Can you give an example?

2023-10-15 01:35 UTC, ruiqurm commented on driver/dtld.c
> +        return -ENOMEM;
I don't have permission to push a commit. So I refactor it in the next PR?

2023-10-15 03:51 UTC, ruiqurm approved these changes

2023-10-15 03:52 UTC, ruiqurm approved these changes

2023-10-15 05:25 UTC, ruiqurm approved these changes

2023-10-15 05:42 UTC, ruiqurm approved these changes

2023-10-15 05:54 UTC, ruiqurm approved these changes
Approve for merging

2023-10-16 01:50 UTC, ruiqurm approved these changes

2023-10-16 02:45 UTC, merged